#!/bin/zsh

go-.oh-my-zsh(){
	curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh |sh;
}
go-zsh-syntax-highlighting(){
	git clone https://www.github.com/zsh-users/zsh-syntax-highlighting.git;
}

cd $HOME; for X in {~/.oh-my-zsh,~/zsh-syntax-highlighting};{ [[ -d $X ]]||go-$X }
