#!/bin/zsh
if [[ $* ]]; then
searchterm="$*"
else
read -p "Enter your search term: " searchterm
fi
searchterm=$(echo $searchterm | sed -e 's/\ /+/g')
elinks "https://www.google.com/search?q=$searchterm"
