#!/bin/zsh

if [[ $PWD != /mnt/c/* ]]
then
	cd /mnt/c/Users/barth/Desktop
fi
tasklist.exe | grep -anPi -- "$*" | grep -aPo -- '^.*\.[a-zA-Z0-9]+[\s]+[0-9]+' | awk '{ print $NF }' >| /tmp/WIN_PROC_MATCH
tasklist.exe | sed -r '1,3d' | grep --color=auto -aPi -- "$*" | grep --color=auto -anPi -- "$*"


